name: minimal_chat_app
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.9.0 # Ensure you have the latest version

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_lints: ^2.0.0 # Use the latest available version
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/chat.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/chat.png
    - assets/icons/ducky.png

  fonts:
    - family: Arima
      fonts:
        - asset: assets/fonts/Arima-VariableFont_wght.ttf
          style: italic
