// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTCkQo3ibQ-vuGbJHqfJaXsGaTIBn9Xs',
    appId: '1:526253976018:web:69c9dedd0e03407c08800b',
    messagingSenderId: '526253976018',
    projectId: 'chatapp-da1bf',
    authDomain: 'chatapp-da1bf.firebaseapp.com',
    storageBucket: 'chatapp-da1bf.appspot.com',
    measurementId: 'G-L05HY2B9DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp040T-p9WNtTWMXSLCbl7fuTS4qEBnGg',
    appId: '1:526253976018:android:86ca0d253445696708800b',
    messagingSenderId: '526253976018',
    projectId: 'chatapp-da1bf',
    storageBucket: 'chatapp-da1bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjqld7-CakobHjvdhisoWwIKxRMX7uLvM',
    appId: '1:526253976018:ios:ea55d58a00bb921508800b',
    messagingSenderId: '526253976018',
    projectId: 'chatapp-da1bf',
    storageBucket: 'chatapp-da1bf.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjqld7-CakobHjvdhisoWwIKxRMX7uLvM',
    appId: '1:526253976018:ios:ea55d58a00bb921508800b',
    messagingSenderId: '526253976018',
    projectId: 'chatapp-da1bf',
    storageBucket: 'chatapp-da1bf.appspot.com',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsTCkQo3ibQ-vuGbJHqfJaXsGaTIBn9Xs',
    appId: '1:526253976018:web:cc93020e4822de8908800b',
    messagingSenderId: '526253976018',
    projectId: 'chatapp-da1bf',
    authDomain: 'chatapp-da1bf.firebaseapp.com',
    storageBucket: 'chatapp-da1bf.appspot.com',
    measurementId: 'G-VFVSX0SLKG',
  );

}